#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "n0n4w3-jj"
email = "story.botsfordli@gmail.com"

[ui]
diff-formatter = ":git"
pager = "delta"
default-command = "log"

[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() & ~mine()"
